name: ci auto rerun failed jobs

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "The run id of the workflow to rerun"
        required: true
      attempts:
        description: "The number of attempts to rerun the workflow"
        required: true
      retries:
        description: "The number of retries to rerun the workflow"
        required: true
      github_repo:
        description: "The repository to rerun the workflow"
        required: false
      distinct_id:
        description: "The distinct id of the workflow to rerun"
        required: false

run-name: ci auto rerun failed jobs - attempt ${{ inputs.attempts }}

jobs:
  gh-cli-rerun:
    name: rerun - attempt ${{ inputs.attempts }}
    permissions:
      actions: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: "${{ secrets.AUTO_RERUN || github.token }}"
      COPILOT_CLI: ${{ secrets.COPILOT_CLI }}
      run_id: ${{ inputs.run_id }}
      attempts: ${{ inputs.attempts }}
      retries: ${{ inputs.retries }}
      github_repo: ${{ inputs.github_repo || github.repository }}
    steps:
      - name: Host - Checkout action ${{ inputs.distinct_id }}
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: config gh copilot cli summary
        if: ${{ env.COPILOT_CLI != '' }}
        run: | # only works with oauth and not PAT https://github.com/github/gh-copilot/issues/1
          unset GITHUB_TOKEN GH_TOKEN
          printf '%s' "${{ secrets.COPILOT_CLI }}" | gh auth login --with-token
          mkdir -p ${HOME}/.config/{gh,gh-copilot}
          printf '%b\n' 'optional_analytics: false\nsuggest_execute_confirm_default: false' > ${HOME}/.config/gh-copilot/config.yml
          printf '%s\n' "GITHUB_TOKEN=$(gh auth token --hostname github.com)" >> $GITHUB_ENV
          printf '%s\n' "GH_TOKEN=$(gh auth token --hostname github.com)" >> $GITHUB_ENV
          gh extension install github/gh-copilot --force

      - name: gh cli rerun and summaries ${{ inputs.distinct_id }}
        if: inputs.attempts <= inputs.retries
        run: |
          failures="$(gh run view ${run_id} --log-failed --repo "${github_repo}" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")"

          if [[ -z "${failures}" ]]; then
              failures="$(gh run view ${run_id} --repo "${github_repo}" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")"
          fi

          if [[ "${retries}" -ge "2" ]]; then
              gh run rerun "${run_id}" --failed --debug --repo "${github_repo}"
          else
              gh run rerun "${run_id}" --failed --repo "${github_repo}"
          fi

          if [[ -n "${{ secrets.COPILOT_CLI }}" ]]; then
              gh copilot explain "${failures}" >> $GITHUB_STEP_SUMMARY
          else
              printf '%s\n' "COPILOT_CLI secret is not set" >> $GITHUB_STEP_SUMMARY
          fi

          printf '%b\n' "# gh cli workflow reruns" >> $GITHUB_STEP_SUMMARY
          printf '\n%b\n' ":octocat: Here is a summary of inputs from the failed workflow" >> $GITHUB_STEP_SUMMARY
          printf '\n%b\n' "ðŸŸ¥ Failures at:\n\n\`\`\`log\n${failures}\n\`\`\`" >> $GITHUB_STEP_SUMMARY
          printf '\n%b\n' "ðŸŸ¦ Attempt: ${attempts} - Rerun failed jobs in ${run_id} :hammer:" >> $GITHUB_STEP_SUMMARY

          if gh run watch ${run_id} --exit-status --repo "${github_repo}"; then
              printf '\n%b\n' "âœ… Attempt: ${attempts} succeeded ðŸ˜º" >> $GITHUB_STEP_SUMMARY
          else
              printf '\n%b\n' "âŒ Attempt: ${attempts} failed ðŸ˜¾" >> $GITHUB_STEP_SUMMARY
          fi
