name: example workflow via composite action

on:
  workflow_dispatch:
    inputs:
      skip_rerun:
        description: "Skip rerun?"
        required: true
        default: false
        type: boolean
      retries:
        description: "Number of rerun retries"
        required: true
        default: "5"
        type: choice
        options: ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

  # schedule:
  #   - cron: "*/5 * * * *" # every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [workflow-example]
        conclusion: ["job-success", "job-failure"]
    steps:
      - name: pass
        if: matrix.conclusion == 'job-success'
        run: exit

      - name: fail
        if: matrix.conclusion == 'job-failure' && github.run_attempt < 3
        run: exit 1

    name: Dummy build job

  release:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: exit

    name: Dummy release job

  ci-auto-rerun-failed-jobs-action:
    if: failure() && (github.event.inputs.skip_rerun || 'false') == 'false'
    needs: [build, release]
    concurrency:
      group: ci-auto-rerun-failed-jobs-action
      cancel-in-progress: true
    permissions:
      actions: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: "${{ secrets.AUTO_RERUN || github.token }}"
      github_repo: "" # To use ci-auto-rerun-failed-jobs-action.yml hosted in a remote repository else default to the current repository. Requires PAT token AUTO_RERUN
      distinct_id: ${{ github.event.inputs.distinct_id }}
      retries: ${{ github.event.inputs.retries || '1' }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: ci-auto-rerun-failed-jobs-action via ${{ env.github_repo || github.repository }}
        run: >
          gh workflow run ci-auto-rerun-failed-jobs-action.yml
          --repo "${{ env.github_repo || github.repository }}"
          -f github_repo=${{ github.repository }}
          -f run_id=${{ github.run_id }}
          -f attempts=${{ github.run_attempt }}
          -f retries=${retries}
          -f distinct_id=${distinct_id}
