name: zizmor workflow audits
on:
  push:
  pull_request:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
   zizmor-workflow-audits:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: zizmor workflow audits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install zizmor
          go install github.com/buildkite/terminal-to-html/v3/cmd/terminal-to-html

          zizmor . --gh-token $GITHUB_TOKEN | terminal-to-html > out.html

          printf '%b\n' "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat out.html >> $GITHUB_STEP_SUMMARY
          printf '%b' "\`\`\`" >> $GITHUB_STEP_SUMMARY




